# Generated by Django 3.1.4 on 2021-01-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AppLogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_time', models.DateTimeField(auto_now_add=True)),
                ('username', models.TextField()),
                ('command', models.TextField()),
            ],
            options={
                'verbose_name': 'Log',
                'verbose_name_plural': 'Logs',
            },
        ),
        migrations.CreateModel(
            name='Iscritti',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('codice_fiscale', models.TextField(unique=True)),
                ('codice_socio', models.TextField()),
                ('nome', models.TextField()),
                ('cognome', models.TextField()),
                ('sesso', models.CharField(choices=[('M', 'Maschio'), ('F', 'Femmina')], max_length=1)),
                ('data_di_nascita', models.DateField()),
                ('comune_di_nascita', models.TextField(default='Avellino')),
                ('indirizzo', models.TextField()),
                ('civico', models.TextField()),
                ('comune', models.TextField(default='Avellino')),
                ('provincia', models.CharField(default='AV', max_length=2)),
                ('cap', models.TextField(default='83100')),
                ('informativa2a', models.BooleanField(default=True, verbose_name='Consenso privacy 2.a')),
                ('informativa2b', models.BooleanField(default=True, verbose_name='Consenso privacy 2.b')),
                ('consenso_immagini', models.BooleanField(default=True, verbose_name='Consenso immagini')),
                ('livello_foca', models.TextField(default=None, null=True)),
                ('coca', models.BooleanField(default=False)),
                ('branca', models.TextField(choices=[('Branca L/C', 'Branca L/C'), ('Branca E/G', 'Branca E/G'), ('Branca R/S', 'Branca R/S'), ('Adulti', 'Co.Ca.')])),
                ('cellulare', models.TextField(blank=True, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('telegram', models.TextField(blank=True, null=True)),
                ('authcode', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('role', models.CharField(choices=[('SA', 'Super Admin'), ('AD', 'Admin'), ('CA', 'Capo'), ('IS', 'Iscritto')], default='IS', max_length=2)),
            ],
            options={
                'verbose_name': 'Iscritto',
                'verbose_name_plural': 'Iscritti',
            },
        ),
    ]
