# Generated by Django 3.1.4 on 2021-01-04 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coca_bot', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iscritti',
            name='telegram_id',
            field=models.TextField(blank=True, null=True),
        ),
    ]
